=== erocci/erocci/schemas/occi.xsd
<!-- -*- mode: nxml -*- -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="0.2.0" >
  <xsd:annotation>
    <xsd:documentation xml:lang="en" >
      OCCI model Description Schema 
      Version 1
      Aligned with the OCCI Core Document
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="schema" type="occiSchema" version="0.2" />

  <xsd:complexType name="occiSchema" >
    <xsd:sequence>
      <xsd:element name="extension" type="occiExtension" />
    </xsd:sequence>
    <xsd:attribute name="version" type="xsd:string" />
  </xsd:complexType>

  <xsd:element name="extension" type="occiExtensionType" />

  <xsd:complexType name="occiExtensionType" >
    <xsd:sequence>
      <xsd:element ref="xsd:annotation" minOccurs="0" maxOccurs="1" />
      <xsd:element name="kind" type="occiKindType" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="mixin" type="occiMixinType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" />
    <xsd:attribute name="version" type="xsd:string" />
    <xsd:attribute name="scheme" type="xsd:anyURI" use="required" >
      <xsd:annotation>
	<xsd:documentation xml:lang="en" >
	  'scheme' attribute is only required for 'extension'
	  elements. If not specified in child elements, 'scheme'
	  attribute is parent element's one.
	</xsd:documentation>
	<xsd:documentation xml:lang="en" >
	  'scheme' attribute can be a fully qualified url or can start
	  with '.'.  In the latter case, '.' must be replaced with
	  parent element's 'scheme' attribute value to get the full
	  scheme url.
	</xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
  </xsd:complexType>

  <xsd:complexType name="occiCategoryType" >
    <xsd:sequence>
      <xsd:element name="annotation" type="occiAnnotationType" minOccurs="0" maxOccurs="1" />
      <xsd:element name="attributes" type="occiAttributesType" />
      <xsd:element name="actions" type="occiActionsType" />
    </xsd:sequence>
    <xsd:attribute name="scheme" type="xsd:anyURI" />
    <xsd:attribute name="term" type="xsd:string" use="required" />
    <xsd:attribute name="title" type="xsd:string" />
    <xsd:attribute name="use" default="required" >
      <xsd:annotation>
	<xsd:documentation xml:lang="en" >
	  If category is 'required', any implementation MUST support
	  this category.  If category is 'optional', implementations
	  SHOULD support this category.
	</xsd:documentation>
      </xsd:annotation>
      <xsd:simpleType>
	<xsd:restriction base="xsd:string" >
 	  <xsd:enumeration name="required" />
	  <xsd:enumeration name="optional" />
	</xsd:restriction>
      </xsd:simpleType>
    </xsd:attribute>
  </xsd:complexType>

  <xsd:complexType name="occiAttributesType" >
    <xsd:sequence>
      <xsd:element name="attribute" type="occiAttributeType" />
      <xsd:element name="instance" type="occiCategoryType" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:copmplexType name="occiActionsType" >
    <xsd:sequence>
      <xsd:element name="action" type="occiActionType" />
    </xsd:sequence>
  </xsd:copmplexType>

  <xsd:complexType name="occiKindType" >
    <xsd:extension base="occiCategoryType" >
      <xsd:attribute name="rel" type="xsd:anyURI" />
      <xsd:attribute name="class" type="xsd:string" fixed="kind" />
    </xsd:extension>
  </xsd:complexType>

  <xsd:complexType name="occiMixinType" >
    <xsd:extension base="occiCategoryType" >
      <xsd:sequence>
	<xsd:element name="relations" type="occiRelationsType" />
      </xsd:sequence>
      <xsd:attribute name="class" type="xsd:string" fixed="mixin" />
    </xsd:extension>
  </xsd:complexType>

  <xsd:complexType name="occiRelationsType" >
    <xsd:sequence>
      <xsd:element name="relation" type="occiRelationType" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="occiRelationType" >
    <xsd:attribute name="id" type="xsd:anyURI" />
  </xsd:complexType>

  <xsd:complexType name="occiAttributeType" >
    <xsd:complexContent>
      <xsd:extension base="xsd:attribute" >
	<xsd:attribute name="immutable" type="xsd:boolean" default="false" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <!--
      Extend annotation to include implementation specific attributes
  -->
  <xsd:complexType name="occiAnnotationType" >
    <xsd:complexContent>
      <xsd:extension base="xsd:annotation" >
	<xsd:sequence>
	  <xsd:element name="attribute" type="occiImplemAttrType" />
	</xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="occiImplemAttrType" >
    <xsd:attribute name="name" type="xsd:string" />
    <xsd:attribute name="value" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="occiActionType" >
    <xsd:sequence>
      <xsd:element ref="xsd:annotation" minOccurs="0" maxOccurs="1" />
      <xsd:element name="attributes" type="occiAttributesType" />
    </xsd:sequence>
    <xsd:attribute name="scheme" type="xsd:anyURI" />
    <xsd:attribute name="term" type="xsd:string" use="required" />    
    <xsd:attribute name="title" type="xsd:string" />
  </xsd:complexType>
</xsd:schema>

=== erocci/erocci/apps/backend_fs/priv/occi-storage.xml
<?xml version="1.0" encoding="UTF-8"?>
<occi:extension xmlns:occi="http://schemas.ogf.org/occi"
		xmlns:xs="http://www.w3.org/2001/XMLSchema"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://schemas.ogf.org/occi occi.xsd " name="Storage"
		status="experimental" version="1">

  <!--
      Storage Container Kind (resource)
  -->
  <occi:kind term="container" scheme="http://schemas.ogf.org/occi/storage#"
	     title="Container Resource (dir)">
    <occi:parent scheme="http://schemas.ogf.org/occi/core#" term="resource" />
    <occi:attribute name="occi.storage.size" type="xs:integer" title="Container Size (#children)" />
  </occi:kind>

  <!--
      Storage Container entry Kind (link)
  -->
  <occi:kind term="containerentry" scheme="http://schemas.ogf.org/occi/storage#"
	     title="Container Entry Link">
    <occi:parent scheme="http://schemas.ogf.org/occi/core#" term="link" />
  </occi:kind>

  <!--
      Data Kind
  -->
  <occi:kind term="data" scheme="http://schemas.ogf.org/occi/storage#"
	     title="Data Resource (file)">
    <occi:parent scheme="http://schemas.ogf.org/occi/core#" term="resource" />
    <occi:attribute name="occi.storage.mimetype" type="xs:string" title="Content Mimetype" />
    <occi:attribute name="occi.storage.size" type="xs:integer" title="Content Size" />
  </occi:kind>

  <!--
      Raw data mixin
  -->
  <occi:mixin term="rawdata" scheme="http://schemas.ogf.org/occi/storage#"
	     title="Raw data mixin">
    <occi:attribute name="occi.storage.raw" type="xs:anyURI" title="Data content link" />
  </occi:mixin>

  <!--
      Thumbnail Mixin
  -->
  <occi:mixin term="thumbnail" scheme="http://schemas.ogf.org/occi/storage#"
	      title="Data thumbnail (light representation)" >
    <occi:attribute name="occi.storage.thumbnail.id" type="xs:anyURI" title="" />
    <occi:attribute name="occi.storage.thumbnail.mimetype" type="xs:string" title="" />
  </occi:mixin>
  
</occi:extension>
